### PR TITLE
Fix pipfile

### PR DESCRIPTION
**Pull request by JamesKunstle**

### CODE REVIEW

**Comment by JamesKunstle** [comment]
@cdolfi Quick review here- lots of whitespace fixes from pre-commit, made one change that's important in the pre-commit config that specifically ignores file 'job_manager' for mypy checks because it's mad about redis but won't allow me to fix it by installing the correct modules, so I'm just ignoring it until it sorts itself out.

**Review by cdolfi — APPROVED** [review]
lgtm, just add signature

**Comment by cdolfi** [comment]
@JamesKunstle when signature is added ill merge

**Comment by JamesKunstle** [comment]
@cdolfi Signature is on commit, Github wants that GPG signature that we agreed was unnecessary.

**Pull request merged**
